[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "googleapis", "google-auth-library", "node-fetch"]
  included_files = ["node_modules/@anthropic-ai/sdk/**", "node_modules/googleapis/**", "node_modules/google-auth-library/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "netlify/functions"
  port = 8888
